name: tiny_tots
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none' 

# Version and build number for the app
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: ^3.7.0

# Dependencies for the app
dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS-style icons
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2

# Development dependencies (used for testing and linting)
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for good coding practices
  flutter_lints: ^5.0.0

# Flutter-specific configuration
flutter:
  # Enables the use of Material Icons
  uses-material-design: true

  # Add assets (images, fonts, etc.)
  assets:
    - assets/splash_logo.png

  # To add custom fonts, uncomment and configure:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700