name: tiny_tots
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none' 

# Version and build number for the app
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: ^3.7.0

# Dependencies for the app
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  
  # Cupertino Icons for iOS-style icons
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.5
  audioplayers: ^6.4.0

# Development dependencies (used for testing and linting)
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for good coding practices
  flutter_lints: ^5.0.0

# Flutter-specific configuration
flutter:
  # Enables the use of Material Icons
  uses-material-design: true

  # Add assets (images, fonts, etc.)
  assets:
    - assets/splash_logo.png

    - assets/images/alphabets.png
    - assets/images/numbers.png
    - assets/images/shapes.png
    - assets/images/colors.png
    - assets/images/animals.png
    - assets/images/birds.png
    - assets/images/poems.png
    - assets/images/exercise.png
    - assets/images/games.png
    - assets/images/puzzles.png
    - assets/images/media.png

 # add soundependency_overrides:
    - assets/sounds/a.mp3
    - assets/sounds/b.mp3
    - assets/sounds/c.mp3
    - assets/sounds/d.mp3
    - assets/sounds/e.mp3
    - assets/sounds/f.mp3
    - assets/sounds/g.mp3
    - assets/sounds/h.mp3
    - assets/sounds/i.mp3
    - assets/sounds/j.mp3
    - assets/sounds/k.mp3
    - assets/sounds/l.mp3
    - assets/sounds/m.mp3
    - assets/sounds/n.mp3
    - assets/sounds/o.mp3
    - assets/sounds/p.mp3
    - assets/sounds/q.mp3
    - assets/sounds/r.mp3
    - assets/sounds/s.mp3
    - assets/sounds/t.mp3
    - assets/sounds/u.mp3
    - assets/sounds/v.mp3
    - assets/sounds/w.mp3
    - assets/sounds/x.mp3
    - assets/sounds/y.mp3
    - assets/sounds/z.mp3

    # Add images for each alphabet letter
    - assets/images/Letter_A.png
    - assets/images/Letter_B.png
    - assets/images/Letter_C.png
    - assets/images/Letter_D.png
    - assets/images/Letter_E.png
    - assets/images/Letter_F.png
    - assets/images/Letter_G.png
    - assets/images/Letter_H.png
    - assets/images/Letter_I.png
    - assets/images/Letter_J.png
    - assets/images/Letter_K.png
    - assets/images/Letter_L.png
    - assets/images/Letter_M.png
    - assets/images/Letter_N.png
    - assets/images/Letter_O.png
    - assets/images/Letter_P.png
    - assets/images/Letter_Q.png
    - assets/images/Letter_R.png
    - assets/images/Letter_S.png
    - assets/images/Letter_T.png
    - assets/images/Letter_U.png
    - assets/images/Letter_V.png
    - assets/images/Letter_W.png
    - assets/images/Letter_X.png
    - assets/images/Letter_Y.png
    - assets/images/Letter_Z.png
  # numbers
    - assets/numbers/1.png
    - assets/numbers/2.png
    - assets/numbers/3.png
    - assets/numbers/4.png
    - assets/numbers/5.png
    - assets/numbers/6.png
    - assets/numbers/7.png
    - assets/numbers/8.png
    - assets/numbers/9.png
    - assets/numbers/10.png
  # shapes
    - assets/images/shapes/circle.png
    - assets/images/shapes/diamond.png
    - assets/images/shapes/hexagon.png
    - assets/images/shapes/oval.png
    - assets/images/shapes/pentagon.png
    - assets/images/shapes/rectangle.png
    - assets/images/shapes/square.png
    - assets/images/shapes/star.png
    - assets/images/shapes/triangle.png

  # animals
    - assets/images/animals/bear.png
    - assets/images/animals/cat.png
    - assets/images/animals/dog.png
    - assets/images/animals/elephant.png
    - assets/images/animals/giraffe.png
    - assets/images/animals/lion.png
    - assets/images/animals/monkey.png
    - assets/images/animals/rabbit.png
    - assets/images/animals/tiger.png
    - assets/images/animals/zebra.png

  # birds
    - assets/images/birds/crow.png
    - assets/images/birds/duck.png
    - assets/images/birds/eagle.png
    - assets/images/birds/owl.png
    - assets/images/birds/parrot.png
    - assets/images/birds/peacock.png
    - assets/images/birds/penguin.png
    - assets/images/birds/pigeon.png
    - assets/images/birds/sparrow.png
    - assets/images/birds/swan.png

  # poems
    - assets/sounds/poems/twinkle.ogg


  # To add custom fonts, uncomment and configure:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700