name: tiny_tots
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none' 

# Version and build number for the app
version: 1.0.0+1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/icon.png"  # Path to your 1024×1024 logo
  adaptive_icon_background: "#FFFFFF"  # For Android adaptive icons
  adaptive_icon_foreground: "assets/logo/icon_foreground.png"

# Dart SDK version
environment:
  sdk: ^3.7.0

# Dependencies for the app
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.5
  audioplayers: ^6.4.0
  shared_preferences: 2.5.3
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  flutter_tts: ^4.2.2
  confetti: ^0.8.0
  youtube_player_flutter: ^9.1.1


# Development dependencies (used for testing and linting)
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for good coding practices
  flutter_lints: ^5.0.0

  flutter_launcher_icons: "^0.13.1"


# Flutter-specific configuration
flutter:
  # Enables the use of Material Icons
  uses-material-design: true

  # Add assets (images, fonts, etc.)
  assets:
    - assets/images/splash_logo.png

    - assets/images/learning.png
    - assets/images/alphabets.png
    - assets/images/numbers.png
    - assets/images/shapes.png
    - assets/images/colors.png
    - assets/images/animals.png
    - assets/images/birds.png
    - assets/images/poems.png
    - assets/images/exercise.png
    - assets/images/games.png
    - assets/images/puzzles.png
    - assets/images/media.png
    - assets/images/emotions.png
    - assets/images/food.png
    - assets/images/fruits.png
    - assets/images/toys.png
    - assets/images/vehicles.png

 # add soundependency_overrides:
    - assets/sounds/a.ogg
    - assets/sounds/b.ogg
    - assets/sounds/c.ogg
    - assets/sounds/d.ogg
    - assets/sounds/e.ogg
    - assets/sounds/f.ogg
    - assets/sounds/g.ogg
    - assets/sounds/h.ogg
    - assets/sounds/i.ogg
    - assets/sounds/j.ogg
    - assets/sounds/k.ogg
    - assets/sounds/l.ogg
    - assets/sounds/m.ogg
    - assets/sounds/n.ogg
    - assets/sounds/o.ogg
    - assets/sounds/p.ogg
    - assets/sounds/q.ogg
    - assets/sounds/r.ogg
    - assets/sounds/s.ogg
    - assets/sounds/t.ogg
    - assets/sounds/u.ogg
    - assets/sounds/v.ogg
    - assets/sounds/w.ogg
    - assets/sounds/x.ogg
    - assets/sounds/y.ogg
    - assets/sounds/z.ogg

    # Add images for each alphabet letter
    - assets/images/Letter_a.png
    - assets/images/Letter_b.png
    - assets/images/Letter_c.png
    - assets/images/Letter_d.png
    - assets/images/Letter_e.png
    - assets/images/Letter_f.png
    - assets/images/Letter_g.png
    - assets/images/Letter_h.png
    - assets/images/Letter_i.png
    - assets/images/Letter_j.png
    - assets/images/Letter_k.png
    - assets/images/Letter_l.png
    - assets/images/Letter_m.png
    - assets/images/Letter_n.png
    - assets/images/Letter_o.png
    - assets/images/Letter_p.png
    - assets/images/Letter_q.png
    - assets/images/Letter_r.png
    - assets/images/Letter_s.png
    - assets/images/Letter_t.png
    - assets/images/Letter_u.png
    - assets/images/Letter_v.png
    - assets/images/Letter_w.png
    - assets/images/Letter_x.png
    - assets/images/Letter_y.png
    - assets/images/Letter_z.png
  # numbers
    - assets/numbers/1.png
    - assets/numbers/2.png
    - assets/numbers/3.png
    - assets/numbers/4.png
    - assets/numbers/5.png
    - assets/numbers/6.png
    - assets/numbers/7.png
    - assets/numbers/8.png
    - assets/numbers/9.png
    - assets/numbers/10.png
  # shapes
    - assets/images/shapes/circle.png
    - assets/images/shapes/diamond.png
    - assets/images/shapes/hexagon.png
    - assets/images/shapes/oval.png
    - assets/images/shapes/pentagon.png
    - assets/images/shapes/rectangle.png
    - assets/images/shapes/square.png
    - assets/images/shapes/star.png
    - assets/images/shapes/triangle.png

  # animals
    - assets/images/animals/bear.png
    - assets/images/animals/cat.png
    - assets/images/animals/dog.png
    - assets/images/animals/elephant.png
    - assets/images/animals/giraffe.png
    - assets/images/animals/lion.png
    - assets/images/animals/monkey.png
    - assets/images/animals/rabbit.png
    - assets/images/animals/tiger.png
    - assets/images/animals/zebra.png
    - assets/images/animals/fish.png

  # birds
    - assets/images/birds/crow.png
    - assets/images/birds/duck.png
    - assets/images/birds/eagle.png
    - assets/images/birds/owl.png
    - assets/images/birds/parrot.png
    - assets/images/birds/peacock.png
    - assets/images/birds/penguin.png
    - assets/images/birds/pigeon.png
    - assets/images/birds/sparrow.png
    - assets/images/birds/swan.png

  # colors
    - assets/images/colors/black.png
    - assets/images/colors/blue.png
    - assets/images/colors/brown.png
    - assets/images/colors/green.png
    - assets/images/colors/orange.png
    - assets/images/colors/pink.png
    - assets/images/colors/purple.png
    - assets/images/colors/red.png
    - assets/images/colors/yellow.png
    - assets/images/colors/white.png

  # puzzle_colors
    - assets/images/puzzle_colors/black.png
    - assets/images/puzzle_colors/blue.png
    - assets/images/puzzle_colors/brown.png
    - assets/images/puzzle_colors/green.png
    - assets/images/puzzle_colors/pink.png
    - assets/images/puzzle_colors/purple.png
    - assets/images/puzzle_colors/red.png
    - assets/images/puzzle_colors/yellow.png
    - assets/images/puzzle_colors/white.png

  # foods
    - assets/images/foods/bread.png
    - assets/images/foods/burger.png
    - assets/images/foods/cake.png
    - assets/images/foods/cookie.png
    - assets/images/foods/donut.png
    - assets/images/foods/icecream.png
    - assets/images/foods/pasta.png
    - assets/images/foods/pizza.png
    - assets/images/foods/sandwich.png
    - assets/images/foods/soup.png

  # fruits
    - assets/images/fruits/apple.png
    - assets/images/fruits/banana.png
    - assets/images/fruits/cherry.png
    - assets/images/fruits/grape.png
    - assets/images/fruits/kiwi.png
    - assets/images/fruits/mango.png
    - assets/images/fruits/orange.png
    - assets/images/fruits/pear.png
    - assets/images/fruits/pineapple.png
    - assets/images/fruits/strawberry.png

  # vehicles
    - assets/images/vehicles/bicycle.png
    - assets/images/vehicles/boat.png
    - assets/images/vehicles/bus.png
    - assets/images/vehicles/car.png
    - assets/images/vehicles/helicopter.png
    - assets/images/vehicles/plane.png
    - assets/images/vehicles/scooter.png
    - assets/images/vehicles/ship.png
    - assets/images/vehicles/train.png
    - assets/images/vehicles/truck.png
    
  # toys
    - assets/images/toys/ball.png
    - assets/images/toys/boat.png
    - assets/images/toys/car.png
    - assets/images/toys/doll.png
    - assets/images/toys/kite.png
    - assets/images/toys/plane.png
    - assets/images/toys/puzzle.png
    - assets/images/toys/robot.png
    - assets/images/toys/teddy.png
    - assets/images/toys/train.png

  # emotions
    - assets/images/emotions/angry.png
    - assets/images/emotions/excited.png
    - assets/images/emotions/happy.png
    - assets/images/emotions/love.png
    - assets/images/emotions/sad.png
    - assets/images/emotions/scared.png
    - assets/images/emotions/shy.png
    - assets/images/emotions/sleepy.png
    - assets/images/emotions/surprised.png
    - assets/images/emotions/tired.png
    
    # poems
    - assets/sounds/poems/twinkle.ogg


  # To add custom fonts, uncomment and configure:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700